name: justrest
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  connectivity: ^3.0.6
  share: ^2.0.4
  url_launcher: ^6.0.17
  country_code_picker: ^2.0.2
  animated_splash_screen: ^1.1.0
  google_fonts: ^2.1.0
  carousel_slider: ^4.0.0
  firebase_core: ^1.10.2
  cloud_firestore: ^3.1.1
  pin_code_fields: ^7.3.0
  firebase_auth: ^3.3.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

